# Generated by Django 4.1.6 on 2023-02-10 03:31

import chat.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userapp',
            managers=[
                ('objects', chat.models.UserAppManager()),
            ],
        ),
    ]
