# Generated by Django 4.1.6 on 2023-02-10 03:42

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userapp_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.UserApp.user_directory_path, verbose_name='photo'),
        ),
    ]
