# Generated by Django 4.1.6 on 2023-02-11 06:17

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_userapp_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='photo_cover',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.UserApp.user_directory_path_for_cover, verbose_name='photo_cover'),
        ),
    ]
