# Generated by Django 4.1.6 on 2023-02-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gander', models.CharField(choices=[('NDF', 'not define'), ('ML', 'male'), ('FML', 'female')], default='NDF', max_length=3, verbose_name='gander')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_date')),
            ],
        ),
        migrations.AddField(
            model_name='userapp',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
