# Generated by Django 4.1.6 on 2023-02-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinformations_userapp_bio_alter_userapp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='more_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userinformations', verbose_name='more_info'),
        ),
    ]
